version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1
jobs:
  build:
    docker:
      - image: cimg/node:15.9.0-browsers
    steps:
      - browser-tools/install-firefox
      - add_ssh_keys:
          fingerprints:
            - "6f:be:b7:31:66:48:ff:80:ca:77:aa:a1:21:8b:18:2b"
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            npm run build:ci
            npm run banana
            npm run start &
            npm test
            ./scripts/zip.sh kai
            ./scripts/zip.sh jio
            ./scripts/sim.sh
      - store_artifacts:
          path: WikipediaKaiOSkai.zip
      - store_artifacts:
          path: WikipediaKaiOSjio.zip
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - persist_to_workspace:
          root: .
          paths:
            - ./gh-pages
  update-sim:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6f:be:b7:31:66:48:ff:80:ca:77:aa:a1:21:8b:18:2b"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Set gh-pages dest based on current branch
          command: |
            echo 'export SIM_DIR=$([ "$CIRCLE_BRANCH" == "main" ] && echo "." || echo "$CIRCLE_BRANCH")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Deploy sim
          command: |
            gh-pages --dotfiles --add --dist ./gh-pages --dest $SIM_DIR -m "[ci skip] Update simulator"
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
      - update-sim:
          requires:
            - build
